#!/usr/bin/env node
/**
 * Generates src/app/env.generated.ts from environment variables for Render builds.
 * Usage: API_BASE_URL=... SUPABASE_URL=... SUPABASE_ANON_KEY=... node scripts/set-env.mjs
 */
import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const outPath = resolve(root, 'src/app/env.generated.ts');

const required = [
  ['API_BASE_URL', process.env.API_BASE_URL],
  ['SUPABASE_URL', process.env.SUPABASE_URL],
  ['SUPABASE_ANON_KEY', process.env.SUPABASE_ANON_KEY],
];

const missing = required.filter(([, value]) => !value?.trim()).map(([name]) => name);
if (missing.length > 0) {
  console.error(`Missing required environment variables: ${missing.join(', ')}`);
  process.exit(1);
}

const escape = (value) => value.replace(/\\/g, '\\\\').replace(/'/g, "\\'");

const content = `/** Generated by scripts/set-env.mjs — do not edit manually. */
export const API_BASE_URL = '${escape(required[0][1].trim())}';
export const SUPABASE_URL = '${escape(required[1][1].trim())}';
export const SUPABASE_ANON_KEY = '${escape(required[2][1].trim())}';
`;

writeFileSync(outPath, content, 'utf8');
console.log(`Wrote ${outPath}`);
