-- =========================================================
-- SERVIHOGAR - SCHEMA SQL PARA SUPABASE
-- Base de datos: PostgreSQL / Supabase
-- =========================================================

-- =========================
-- LIMPIEZA OPCIONAL
-- =========================
-- Usa esto solo si quieres reiniciar todo el esquema.
-- Si ya tienes datos importantes, NO ejecutes esta parte.

drop table if exists valoraciones cascade;
drop table if exists cotizaciones cascade;
drop table if exists imagenes_solicitud cascade;
drop table if exists solicitudes_servicio cascade;
drop table if exists portafolio_tecnico cascade;
drop table if exists documentos_tecnico cascade;
drop table if exists tecnico_zonas cascade;
drop table if exists tecnico_categorias cascade;
drop table if exists administradores cascade;
drop table if exists tecnicos cascade;
drop table if exists clientes cascade;
drop table if exists categorias_servicio cascade;
drop table if exists zonas cascade;
drop table if exists ciudades cascade;
drop table if exists usuarios cascade;

-- =========================================================
-- TABLA: usuarios
-- Conectada con Supabase Auth mediante auth_user_id
-- =========================================================

create table usuarios (
    id_usuario bigint generated by default as identity primary key,
    auth_user_id uuid unique references auth.users(id) on delete cascade,
    nombres varchar(100) not null,
    apellidos varchar(100) not null,
    telefono varchar(20),
    foto_perfil_url text,
    estado varchar(20) not null default 'activo',
    fecha_registro timestamp with time zone not null default now(),

    constraint chk_usuarios_estado
        check (estado in ('activo', 'inactivo', 'bloqueado'))
);

-- =========================================================
-- TABLA: clientes
-- Perfil cliente de un usuario
-- =========================================================

create table clientes (
    id_cliente bigint generated by default as identity primary key,
    id_usuario bigint not null unique references usuarios(id_usuario) on delete cascade,
    fecha_alta timestamp with time zone not null default now(),
    estado varchar(20) not null default 'activo',

    constraint chk_clientes_estado
        check (estado in ('activo', 'inactivo'))
);

-- =========================================================
-- TABLA: tecnicos
-- Perfil técnico de un usuario
-- =========================================================

create table tecnicos (
    id_tecnico bigint generated by default as identity primary key,
    id_usuario bigint not null unique references usuarios(id_usuario) on delete cascade,
    descripcion text,
    experiencia_anios int not null default 0,
    estado_validacion varchar(20) not null default 'pendiente',
    fecha_solicitud_validacion timestamp with time zone not null default now(),
    fecha_validacion timestamp with time zone,

    constraint chk_tecnicos_experiencia
        check (experiencia_anios >= 0),

    constraint chk_tecnicos_estado_validacion
        check (estado_validacion in ('pendiente', 'validado', 'rechazado', 'suspendido'))
);

-- =========================================================
-- TABLA: administradores
-- Perfil administrativo del usuario
-- Sin cargo, porque el sistema maneja un rol administrativo simple
-- =========================================================

create table administradores (
    id_administrador bigint generated by default as identity primary key,
    id_usuario bigint not null unique references usuarios(id_usuario) on delete cascade,
    estado varchar(20) not null default 'activo',
    fecha_asignacion timestamp with time zone not null default now(),

    constraint chk_administradores_estado
        check (estado in ('activo', 'inactivo'))
);

-- =========================================================
-- TABLA: ciudades
-- =========================================================

create table ciudades (
    id_ciudad bigint generated by default as identity primary key,
    nombre varchar(100) not null,
    departamento varchar(100) not null,
    pais varchar(100) not null default 'Perú',
    estado varchar(20) not null default 'activo',

    constraint chk_ciudades_estado
        check (estado in ('activo', 'inactivo')),

    constraint uq_ciudad_departamento_pais
        unique (nombre, departamento, pais)
);

-- =========================================================
-- TABLA: zonas
-- Cada zona pertenece a una ciudad
-- =========================================================

create table zonas (
    id_zona bigint generated by default as identity primary key,
    id_ciudad bigint not null references ciudades(id_ciudad) on delete restrict,
    nombre varchar(100) not null,
    estado varchar(20) not null default 'activo',

    constraint chk_zonas_estado
        check (estado in ('activo', 'inactivo')),

    constraint uq_zona_ciudad
        unique (id_ciudad, nombre)
);

-- =========================================================
-- TABLA: categorias_servicio
-- =========================================================

create table categorias_servicio (
    id_categoria bigint generated by default as identity primary key,
    nombre varchar(100) not null unique,
    descripcion text,
    estado varchar(20) not null default 'activo',
    fecha_creacion timestamp with time zone not null default now(),

    constraint chk_categorias_estado
        check (estado in ('activo', 'inactivo'))
);

-- =========================================================
-- TABLA: tecnico_categorias
-- Un técnico puede ofrecer varias categorías
-- =========================================================

create table tecnico_categorias (
    id_tecnico bigint not null references tecnicos(id_tecnico) on delete cascade,
    id_categoria bigint not null references categorias_servicio(id_categoria) on delete restrict,
    fecha_asignacion timestamp with time zone not null default now(),

    primary key (id_tecnico, id_categoria)
);

-- =========================================================
-- TABLA: tecnico_zonas
-- Un técnico puede atender varias zonas
-- =========================================================

create table tecnico_zonas (
    id_tecnico bigint not null references tecnicos(id_tecnico) on delete cascade,
    id_zona bigint not null references zonas(id_zona) on delete restrict,
    fecha_asignacion timestamp with time zone not null default now(),

    primary key (id_tecnico, id_zona)
);

-- =========================================================
-- TABLA: documentos_tecnico
-- Documentos privados para validar al técnico
-- =========================================================

create table documentos_tecnico (
    id_documento bigint generated by default as identity primary key,
    id_tecnico bigint not null references tecnicos(id_tecnico) on delete cascade,
    tipo_documento varchar(50) not null,
    url_documento text not null,
    estado_revision varchar(20) not null default 'pendiente',
    observacion text,
    fecha_subida timestamp with time zone not null default now(),

    constraint chk_documentos_tipo
        check (tipo_documento in ('dni', 'certificado', 'recibo_servicio', 'evidencia_experiencia', 'otro')),

    constraint chk_documentos_estado
        check (estado_revision in ('pendiente', 'aprobado', 'rechazado'))
);

-- =========================================================
-- TABLA: portafolio_tecnico
-- Fotos públicas de trabajos realizados por el técnico
-- =========================================================

create table portafolio_tecnico (
    id_portafolio bigint generated by default as identity primary key,
    id_tecnico bigint not null references tecnicos(id_tecnico) on delete cascade,
    titulo varchar(150) not null,
    descripcion text,
    imagen_url text not null,
    estado varchar(20) not null default 'visible',
    fecha_subida timestamp with time zone not null default now(),

    constraint chk_portafolio_estado
        check (estado in ('visible', 'oculto'))
);

-- =========================================================
-- TABLA: solicitudes_servicio
-- Solicitudes publicadas por clientes
-- =========================================================

create table solicitudes_servicio (
    id_solicitud bigint generated by default as identity primary key,
    id_cliente bigint not null references clientes(id_cliente) on delete restrict,
    id_categoria bigint not null references categorias_servicio(id_categoria) on delete restrict,
    id_zona bigint not null references zonas(id_zona) on delete restrict,
    titulo varchar(150) not null,
    descripcion text not null,
    direccion_referencia text,
    direccion_exacta text,
    estado varchar(20) not null default 'pendiente',
    fecha_publicacion timestamp with time zone not null default now(),
    fecha_actualizacion timestamp with time zone not null default now(),

    constraint chk_solicitudes_estado
        check (estado in ('pendiente', 'en_proceso', 'finalizada', 'cancelada'))
);

-- =========================================================
-- TABLA: imagenes_solicitud
-- Varias imágenes por solicitud
-- =========================================================

create table imagenes_solicitud (
    id_imagen bigint generated by default as identity primary key,
    id_solicitud bigint not null references solicitudes_servicio(id_solicitud) on delete cascade,
    imagen_url text not null,
    descripcion text,
    fecha_subida timestamp with time zone not null default now()
);

-- =========================================================
-- TABLA: cotizaciones
-- Propuestas enviadas por técnicos a solicitudes
-- =========================================================

create table cotizaciones (
    id_cotizacion bigint generated by default as identity primary key,
    id_solicitud bigint not null references solicitudes_servicio(id_solicitud) on delete cascade,
    id_tecnico bigint not null references tecnicos(id_tecnico) on delete restrict,
    monto numeric(10,2) not null,
    descripcion text not null,
    tiempo_estimado varchar(100),
    estado varchar(20) not null default 'pendiente',
    fecha_envio timestamp with time zone not null default now(),
    fecha_actualizacion timestamp with time zone not null default now(),

    constraint chk_cotizaciones_monto
        check (monto > 0),

    constraint chk_cotizaciones_estado
        check (estado in ('pendiente', 'aceptada', 'rechazada', 'retirada')),

    constraint uq_cotizacion_solicitud_tecnico
        unique (id_solicitud, id_tecnico)
);

-- Solo puede existir una cotización aceptada por solicitud.
create unique index uq_cotizacion_aceptada_por_solicitud
on cotizaciones (id_solicitud)
where estado = 'aceptada';

-- =========================================================
-- TABLA: valoraciones
-- Una valoración corresponde a una cotización aceptada/finalizada
-- =========================================================

create table valoraciones (
    id_valoracion bigint generated by default as identity primary key,
    id_cotizacion bigint not null unique references cotizaciones(id_cotizacion) on delete restrict,
    puntuacion int not null,
    comentario text,
    puntualidad int,
    calidad int,
    precio int,
    trato int,
    fecha_valoracion timestamp with time zone not null default now(),

    constraint chk_valoraciones_puntuacion
        check (puntuacion between 1 and 5),

    constraint chk_valoraciones_puntualidad
        check (puntualidad is null or puntualidad between 1 and 5),

    constraint chk_valoraciones_calidad
        check (calidad is null or calidad between 1 and 5),

    constraint chk_valoraciones_precio
        check (precio is null or precio between 1 and 5),

    constraint chk_valoraciones_trato
        check (trato is null or trato between 1 and 5)
);

-- =========================================================
-- ÍNDICES RECOMENDADOS
-- =========================================================

create index idx_usuarios_auth_user_id on usuarios(auth_user_id);

create index idx_zonas_ciudad on zonas(id_ciudad);

create index idx_tecnicos_usuario on tecnicos(id_usuario);
create index idx_tecnicos_estado_validacion on tecnicos(estado_validacion);

create index idx_solicitudes_cliente on solicitudes_servicio(id_cliente);
create index idx_solicitudes_categoria on solicitudes_servicio(id_categoria);
create index idx_solicitudes_zona on solicitudes_servicio(id_zona);
create index idx_solicitudes_estado on solicitudes_servicio(estado);

create index idx_cotizaciones_solicitud on cotizaciones(id_solicitud);
create index idx_cotizaciones_tecnico on cotizaciones(id_tecnico);
create index idx_cotizaciones_estado on cotizaciones(estado);

create index idx_valoraciones_cotizacion on valoraciones(id_cotizacion);

-- =========================================================
-- COMENTARIOS DESCRIPTIVOS
-- =========================================================

comment on table usuarios is 'Perfil principal de los usuarios de ServiHogar, vinculado con Supabase Auth.';
comment on table clientes is 'Perfil cliente asociado a un usuario.';
comment on table tecnicos is 'Perfil técnico asociado a un usuario.';
comment on table administradores is 'Perfil administrativo asociado a un usuario.';
comment on table ciudades is 'Ciudades donde opera la plataforma.';
comment on table zonas is 'Zonas o sectores pertenecientes a una ciudad.';
comment on table categorias_servicio is 'Categorías de servicios domésticos ofrecidos.';
comment on table tecnico_categorias is 'Categorías que puede atender un técnico.';
comment on table tecnico_zonas is 'Zonas donde puede atender un técnico.';
comment on table documentos_tecnico is 'Documentos subidos por técnicos para validación.';
comment on table portafolio_tecnico is 'Fotos públicas de trabajos realizados por técnicos.';
comment on table solicitudes_servicio is 'Solicitudes de servicio publicadas por clientes.';
comment on table imagenes_solicitud is 'Imágenes asociadas a solicitudes de servicio.';
comment on table cotizaciones is 'Cotizaciones enviadas por técnicos a solicitudes.';
comment on table valoraciones is 'Valoraciones realizadas sobre servicios contratados.';


-- =========================================================
-- FUNCIÓN PARA ACTUALIZAR fecha_actualizacion
-- =========================================================

create or replace function actualizar_fecha_actualizacion()
returns trigger as $$
begin
    new.fecha_actualizacion = now();
    return new;
end;
$$ language plpgsql;

create trigger trg_actualizar_fecha_solicitudes
before update on solicitudes_servicio
for each row
execute function actualizar_fecha_actualizacion();

create trigger trg_actualizar_fecha_cotizaciones
before update on cotizaciones
for each row
execute function actualizar_fecha_actualizacion();

create index idx_tecnico_categorias_categoria 
on tecnico_categorias(id_categoria);

create index idx_tecnico_zonas_zona 
on tecnico_zonas(id_zona);

create index idx_documentos_tecnico 
on documentos_tecnico(id_tecnico);

create index idx_portafolio_tecnico 
on portafolio_tecnico(id_tecnico);

create index idx_imagenes_solicitud 
on imagenes_solicitud(id_solicitud);